export {default as HeroImage} from "./images/hero.png";
export { default as SliderImage1} from "./images/1.png";
export { default as SliderImage2} from "./images/2.png";
export { default as SliderImage3} from "./images/3.png";
export {default as TargetIcon} from "./icons/icon_5.svg";
export { default as PerformanceIcon} from "./icons/icon_2.svg";
export { default as SecurityIcon} from "./icons/icon_3.svg";
export { default as QualityIcon} from "./icons/icon_4.svg";
export { default as clockIcon} from "./icons/clock_3.svg";
export { default as HeartIcon} from "./icons/heart_2.svg";
export { default as TickIcon} from "./icons/Path_4402.svg";
export { default as AwardIcon} from "./icons/Path_4406.svg";
export { default as ProjectImage1} from "./images/image_1.png";
export { default as FooterImage} from "./images/footer_img.png";
export { default as CarouselBtn1} from "./icons/carousel_btn1.svg";
export { default as CarouselBtn2} from "./icons/carousel_btn2.svg";
export { default as Quotemarks} from "./icons/Quotemarks-left.svg";
export { default as DevelopmentIcon} from "./icons/development_icon.svg";
export {default as ArrowIcon} from "./icons/arrow.svg";